---
- name: config ocp
  hosts: ocp-demo
  connection: local
  gather_facts: no

  tasks:
  - name: create namespaces
    k8s:
     name: "{{ item }}"
     api_version: v1
     kind: Namespace
     state: present
    with_items:
     - fuse-online
     - maxim-test
